version: '3.3'

services:

  db:
    image: postgres:13.2
    #container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file: 
      - ./.env

  frontend:
    image: marygor/foodgram_frontend:latest
    volumes:
      - frontend_data:/app/build/

  backend:
    image: marygor/foodgram-project-react:latest
    restart: always
    volumes: 
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
  
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_data:/usr/share/nginx/html/
      - ./backend/docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./backend//docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    restart: always

    depends_on:
      - backend
      - frontend

volumes: 
  postgres_data:
  static_value:
  media_value:
  frontend_data:
